### ISSUE TITLE
Error modal turns itself back-on if user closes it before the timeout

### ISSUE THREAD

**Issue by jnovembre** [NovembreLab/ggv#10]
Our "toggle" solution is not ideal...

**Comment by danielecook** [comment]
I put together an alternative to the modal. If you like it I can setup a pull request.

![modal_alt](https://cloud.githubusercontent.com/assets/1536935/24387794/d90ced1c-133c-11e7-9ce6-7c34648b4ad1.gif)

**Comment by danielecook** [comment]
I have implemented the alternative. The help modal details examples.
