### ISSUE TITLE
Add comma's to ucscLink

### ISSUE THREAD

**Issue by danielecook** [NovembreLab/ggv#20]
Let me know if this is helpful. Easy to add.

<img width="274" alt="screen shot 2017-03-27 at 10 52 00 pm" src="https://cloud.githubusercontent.com/assets/1536935/24388408/0287af62-1340-11e7-92e4-7dd8676d3550.png">

**Comment by jnovembre** [comment]
I like it!

**Comment by danielecook** [comment]
Ok I will add!
