### ISSUE TITLE
Querying for variant not in dataset makes a random query 

### ISSUE THREAD

**Issue by aabiddanda** [NovembreLab/ggv#8]
To replicate the error:

1. Switch dataset to `ExAC` or `PopRes` 
2. Type in either `rs548263598`  or `chr21:9411264` into search box
3. Hit Question Mark button to search (repeat as many times as you like)

Upon hitting the question mark, you are taken to a random SNP in the dataset (either `ExAC` or `PopRes`) when you ideally would like for there to be a dropdown window telling you that the SNP was not found in this particular dataset. Hitting the question mark more times gives you new random snps within each dataset. 

If you change the dataset to either one of the 1000 genomes, you get the correct display because it is in the dataset. Additionally, hitting the question mark more times does not change the GGV display in any way.

**Comment by jnovembre** [comment]
Try it now - we've put a temporary alert modal in.  What do you think?

**Comment by aabiddanda** [comment]
A nice fix, the message on the alert could be that the "variant is not found in this dataset"? I also like that the alert disappears after a little while (~2 seconds on chrome - which may be a little long)
